### ISSUE TITLE
Error on v1.3.2 with paper-mc

### ISSUE THREAD

**Issue by 0-0-6** [zwarunek/TimeMachine#1]
running TimeMachine v1.3.2 on Paper version git-Paper-216 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

I get an error with 

[19:08:54 INFO]: [TimeMachine] Enabling TimeMachine v1.3.2                                                                                                                                   
[19:08:54 INFO]:  _______             __  ___         __   _                                  
[19:08:54 INFO]: /_  __(_)_ _  ___   /  |/  /__ _____/ /  (_)__  ___ 
[19:08:54 INFO]:  / / / /  ' \/ -_) / /|_/ / _ ```/ __/ _ \/ / _ \/ -_)                         
[19:08:54 INFO]: /_/ /_/_/_/_/\__/ /_/  /_/\_,_/\__/_//_/_/_//_/\__/ 
[19:08:54 INFO]:         Version 1.3.2                                                        
[19:08:54 INFO]:         Author  Warunek                                                                                                                                                     
[19:08:54 INFO]: *************************************************************Warunek         
[19:08:54 ERROR]: Error occurred while enabling TimeMachine v1.3.2 (Is it up to date?)                                                                                                       
java.lang.ExceptionInInitializerError: null                                                   
        at com.github.zwarunek.timemachine.TimeMachine.onEnable(TimeMachine.java:67) ~[?:?]                                                                                                  
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-216]                                                                                     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-216]                                                               
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-216]                                                              
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-216]                                                                
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-216]  
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:205) ~[patched_1.16.3.jar:git-Paper-216]                                                                  
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-216]                                                                     
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]                                                            
        at java.lang.Thread.run(Thread.java:832) [?:?]                                        
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!                                                                                           
        at org.bstats.bukkit.Metrics.<clinit>(Metrics.java:42) ~[?:?]                                                                                                                        
        ... 10 more                                                                                                                                                                          
[19:08:54 INFO]: [TimeMachine] Disabling TimeMachine v1.3.2                                                                                                                                  
[19:08:54 ERROR]: Error occurred while disabling TimeMachine v1.3.2 (Is it up to date?)       
java.lang.NullPointerException: null                                                          
        at com.github.zwarunek.timemachine.TimeMachine.onDisable(TimeMachine.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-216]                                                                             
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-216]                                                              
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-216]                                                             
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-216]                                                               
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-216]                                                              
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-216]                                                                
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-216]                                                               
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:205) ~[patched_1.16.3.jar:git-Paper-216]                                                     
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-216]                                                                     
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-216]                                                            
        at java.lang.Thread.run(Thread.java:832) [?:?]                                        

This looks like an error with bStats as version 1.3.1 loads for me

**Comment by zwarunek** [comment]
I will look into this and get a fix before the next update. For now, just use v1.3.1 as the only difference is bStats. The update should release in the next week or so.

**Comment by zwarunek** [comment]
Could you possibly replicate this and then send me the folder structure of your server?

**Comment by 0-0-6** [comment]
full folder it too big to attach
[paper-mc-test-without-jar's.zip](https://github.com/zwarunek/TimeMachine/files/5351643/paper-mc-test-without-jar.s.zip)
 ( full at : https://ufile.io/i09nyvgu) but attached everything without jar's here. 

replication is just starting a paper server from scratch with only time machine installed.
Im running on a debian vm:  Linux 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
with openjdk : 
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Debian-1)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Debian-1, mixed mode, sharing)


below is the full tree of the folder
.
├── banned-ips.json
├── banned-players.json
├── bukkit.yml
├── cache
│   ├── mojang_1.16.3.jar
│   └── patched_1.16.3.jar
├── commands.yml
├── eula.txt
├── help.yml
├── logs
│   ├── 2020-10-08-1.log.gz
│   ├── 2020-10-08-2.log.gz
│   └── latest.log
├── minecraft_server_paper.1.16.3.jar
├── ops.json
├── paper.yml
├── permissions.yml
├── plugins
│   ├── bStats
│   │   └── config.yml
│   ├── TimeMachine
│   │   └── config.yml
│   └── TimeMachine-1.3.2.jar
├── server.properties
├── spigot.yml
├── start.sh
├── usercache.json
├── version_history.json
├── whitelist.json
├── world
│   ├── data
│   │   └── raids.dat
│   ├── datapacks
│   │   └── bukkit
│   │       └── pack.mcmeta
│   ├── level.dat
│   ├── level.dat_old
│   ├── playerdata
│   ├── poi
│   ├── region
│   │   └── r.0.-1.mca
│   ├── session.lock
│   └── uid.dat
├── world_nether
│   ├── DIM-1
│   │   ├── data
│   │   │   └── raids.dat
│   │   ├── poi
│   │   └── region
│   │       ├── r.0.0.mca
│   │       ├── r.0.-1.mca
│   │       ├── r.-1.0.mca
│   │       └── r.-1.-1.mca
│   ├── level.dat
│   ├── level.dat_old
│   ├── session.lock
│   └── uid.dat
└── world_the_end
    ├── DIM1
    │   ├── data
    │   │   └── raids_end.dat
    │   ├── poi
    │   └── region
    │       ├── r.0.0.mca
    │       ├── r.0.-1.mca
    │       ├── r.-1.0.mca
    │       └── r.-1.-1.mca
    ├── level.dat
    ├── level.dat_old
    ├── session.lock
    └── uid.dat

**Comment by zwarunek** [comment]
I have fixed the issue. It had to do with the bStats implementation. The fix is out and in version 1.3.3
