### ISSUE TITLE
Logs being spammed with null pointer exceptions

### ISSUE THREAD

**Issue by ssjw** [zwarunek/TimeMachine#2]
I'm getting a stream of these errors in the log files.  Any ideas?

[18:17:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TimeMachine v1.4.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2275) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.github.zwarunek.timemachine.util.ItemListener.onInventoryClick(ItemListener.java:96) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
        ... 18 more

**Comment by zwarunek** [comment]
Is this on version 1.4.2? If so, I can try to recreate this and get a patch out very soon. If not, update to that version

**Comment by ssjw** [comment]
Yes, with 1.4.2.  on Spigot server version 1.16.4.  Let me know if there any other diagnostics I can send to help diagnose.  Software engineer here, though I've successfully avoided having to use Java my entire career.

**Comment by zwarunek** [comment]
Okay I have not done testing on 1.16.4 yet. I will tonight and hopefully find and fix these bugs. Thanks

**Comment by zwarunek** [comment]
I am pretty confident I just patched this one. I didn't check if the metadata for one of the buttons was null. Will be fixed in 1.4.3 probably tomorrow.

**Comment by ssjw** [comment]
Great, thanks!
